SectionDevice."Line1" {
	Comment "Chat"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw${CardId},0"
	}
}

SectionDevice."Speaker1" {
	Comment "System"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw${CardId},1"
	}
}

SectionDevice."Line2" {
	Comment "Chat"

	Value {
		CapturePriority 100
		CapturePCM "hw${CardId},0"
	}
}

SectionDevice."Line3" {
	Comment "Mix"

	Value {
		CapturePriority 100
		CapturePCM "hw${CardId},1"
	}
}