Include.pcm_split.File "/common/pcm/split.conf"

Macro.playback.SplitPCM {
	Name "rodecaster_pro_ii_stereo_out"
    Direction Playback
    Channels 2
    HWChannels 10
	HWChannelPos0 FL	# System Out Left
	HWChannelPos1 FR	# System Out Left
	HWChannelPos2 FL	# Game Out Left
	HWChannelPos3 FR	# Game Out Right
	HWChannelPos4 FL	# Music Out Left
	HWChannelPos5 FR	# Music Out Right
	HWChannelPos6 FL	# Virtual A Out Left
	HWChannelPos7 FR	# Virtual A Out Right
	HWChannelPos8 FL	# Virtual B Out Left
	HWChannelPos9 FR	# Virtual B Out Right
}

Macro.capture.SplitPCM {
	Name "rodecaster_pro_ii_stereo_in"
	Direction Capture
	Channels 2
	HWChannels 2
	HWChannelPos0 FL
	HWChannelPos1 FR
}

SectionDevice."SystemOut" {
    Comment "System"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		HWChannels 10
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."GameOut" {
    Comment "Game"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		HWChannels 10
		Channels 2
		Channel0 2
		Channel1 3
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."MusicOut" {
    Comment "Music"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		HWChannels 10
		Channels 2
		Channel0 4
		Channel1 5
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."VirtualAOut" {
    Comment "Virtual A"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		HWChannels 10
		Channels 2
		Channel0 6
		Channel1 7
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."VirtualBOut" {
    Comment "Virtual B"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		HWChannels 10
		Channels 2
		Channel0 8
		Channel1 9
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."MixIn" {
    Comment "Mix"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		HWChannels 2
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}