# The RODECaster Pro II has two USB ports with different PIDs.
# USB1 has the capability to expose additional audio channel of the device (Game, Music, System...).
# The Multitrack functionality can be toggled on the device itself.
# The device presents itself on USB1 with additional PIDs depending on which configuration is currently selected.

Comment "RODECaster Pro II USB"
if.usb1 {
    Condition {
        Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0037"
    }
    True {
        # Multitrack is disabled for Input and Output
        SectionUseCase."HiFi" {
            Comment "RODECaster Pro II"
            File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-HiFi.conf"
        }
    }
}
If.usb1_multitrack {
    Condition {
        Type String
        Haystack "${CardComponents}"
        Needle "USB19f7:0072"
    }
    True {
        # Multitrack is enabled for Input and Output
        SectionUseCase."HiFi" {
            Comment "RODECaster Pro II with Multitrack"
            File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-HiFi.conf"
        }
    }
}
If.usb1_multitrack_in {
    Condition {
        Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0078"
    }
    True {
        # Multitrack is only for Input enabled
        SectionUseCase."HiFi" {
            Comment "RODECaster Pro II with Multitrack Input"
            File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-In-HiFi.conf"
        }
    }
}
If.usb1_multitrack_out {
    Condition {
        Type String
        Haystack "${CardComponents}"
        Needle "USB19f7:0030"
    }
    True {
        # Multitrack is only for Output enabled
        SectionUseCase."HiFi" {
            Comment "RODECaster Pro II with Multitrack Output"
            File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-In-HiFi.conf"
        }
    }
}

If.usb2 {
    Condition {
        Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0026"
    }
    True {

    }
}