SectionDevice."Line1" {
	Comment "Chat"

	Value {
		PlaybackPCM "hw:${CardId},0"
		JackControl "Playback Channel Map"
	}
}

SectionDevice."Speaker" {
	Comment "System"

	Value {
		PlaybackPCM "hw:${CardId},1"
		JackControl "Playback Channel Map"
	}
}

SectionDevice."Mic" {
	Comment "Chat"

	Value {
		CapturePCM "hw:${CardId},0"
		JackControl "Capture Channel Map"
	}
}

SectionDevice."Line2" {
	Comment "Mix"

	Value {
		CapturePCM "hw:${CardId},1"
		JackControl "Capture Channel Map"
	}
}
