Include.pcm_split.File "/common/pcm/split.conf"

Macro.playback.SplitPCM {
	Name "rodecaster_pro_ii_stereo_out"
	Direction Playback
	Channels 2
	HWChannels 2
	HWChannelPos0 FL
	HWChannelPos1 FR
}

Macro.capture.SplitPCM {
	Name "rodecaster_pro_ii_stereo_in"
	Direction Capture
	Channels 2
	HWChannels 2
	HWChannelPos0 FL
	HWChannelPos1 FR
}

SectionDevice."SystemOut" {
	Comment "System"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		HWChannels 2
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."MixIn" {
	Comment "Mix"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		HWChannels 2
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}