# The RODECaster Pro II has two USB ports, each with its own PID.
# USB1 has additionally the special capability to send multiple additional tracks (multitrack mode).
# The multitrack functionality can be configured for output and input individually.
# This sound card also provides two devices on USB1. Device 0 is always the Mic/Chat Track.
# Device 1 is the optional multitrack device.
Comment = "RODECaster Pro II USB"

Comment "RODECaster Pro II USB"
If.usb1 {
	Condition {
		Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0037"
	}
	True {
		# Multitrack is disabled for Input and Output
		SectionUseCase."HiFi" {
			Comment "RODECaster Pro II"
			File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-HiFi.conf"
		}
	}
}
# If.usb1_multitrack {
# 	Condition {
# 		Type String
# 		Haystack "${CardComponents}"
# 		Needle "USB19f7:0072"
# 	}
# 	True {
# 		# Multitrack is enabled for Input and Output
# 		# todo: write SectionUseCase
# 	}
# }
# If.usb1_multitrack_in {
# 	Condition {
# 		Type String
# 		Haystack "${CardComponents}"
# 		Needle "USB19f7:0078"
# 	}
# 	True {
# 		# Multitrack is only for Input enabled
# 		# todo: write SectionUseCase
# 	}
# }
# If.usb1_multitrack_out {
# 	Condition {
# 		Type String
# 		Haystack "${CardComponents}"
# 		Needle "USB19f7:0030"
# 	}
# 	True {
# 		# Multitrack is only for Output enabled
# 		# todo: write SectionUseCase
# 	}
# }
#
# If.usb2 {
# 	Condition {
# 		Type String
# 		Haystack "${CardComponents}"
# 		Needle "USB19f7:0026"
# 	}
# 	True {
# 		# todo: write SectionUseCase
# 	}
# }
